/*
 * To change thi            @Override
            public boolean accept(File f) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public String getDescription() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }   @Override
    public boolean accept(File f) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getDescription() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
s license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpack;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

/**
 *
 * @author Florian Rauchenzauner & Daniel Popovic
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public String sourceTree = "";
    public LinkedList<tspoFile> tspofiles = new LinkedList<>();
    public JTable jTable_tab_start = new JTable();

    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jFrame_ST.setLocationRelativeTo(null);
        jFrame_Vergleich.setLocationRelativeTo(null);
        fileChooser.setLocation(this.getX(), this.getY());
        jFrame_autosuche.setLocationRelativeTo(null);
        
        jTable_tab_start.setModel(new DefaultTableModel(new String[]{"id", "Übersetzung"}, 10000));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-hd.png")));
        jFrame_Vergleich.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-hd.png")));
        jFrame_autosuche.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-hd.png")));
        jFrame_Save_in_ST.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-hd.png")));
  
        
        jFrame_Vergleich.setContentPane(jScrollPaneVgl);
        jFrame_ST.setVisible(false);
        jTabbedPane.setVisible(false);
        
        this.setSize(500, 500);
        this.setVisible(true);

        File st_new = new File("ST.txt");

        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(st_new));
            sourceTree = (String) ois.readObject();
            jMenuItem_autosuche.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jButton_ST_abbr = new javax.swing.JButton();
        jFrame_autosuche = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_translations = new javax.swing.JComboBox<>();
        jButton_autosuche_ok = new javax.swing.JButton();
        jFrame_ST = new javax.swing.JFrame();
        jButton_ST_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ST_pfad = new javax.swing.JTextField();
        jCheckBox_STbeibehalten = new javax.swing.JCheckBox();
        jFrame_Save_in_ST = new javax.swing.JFrame();
        jButton_OK = new javax.swing.JButton();
        jButton_Abbrechen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_fileFormat = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_exDateipfad = new javax.swing.JTextPane();
        jFrame_Vergleich = new javax.swing.JFrame();
        jScrollPaneVgl = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Vergleichskriterien = new javax.swing.JComboBox<>();
        jComboBox_t1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_t2 = new javax.swing.JComboBox<>();
        jButton_vergleiche_Tab = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_vgl_translation = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_datei = new javax.swing.JMenu();
        jMenuItem_neuesfile = new javax.swing.JMenuItem();
        jMenuItem_oeffnen = new javax.swing.JMenuItem();
        jMenuItem_autosuche = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem_speichern = new javax.swing.JMenuItem();
        jMenuItem_speichernST = new javax.swing.JMenuItem();
        jMenu_extras = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Übersetzung öffnen");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Übersetzungen (.po,.ts)", "ts","po")
        );
        fileChooser.setToolTipText("");

        jButton_ST_abbr.setText("Abbrechen");
        jButton_ST_abbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ST_abbrActionPerformed(evt);
            }
        });

        jFrame_autosuche.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame_autosuche.setResizable(false);

        jLabel2.setText("Folgende Übersetzungen wurden gefunden:");

        jComboBox_translations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_autosuche_ok.setText("Übersetzung öffnen!");
        jButton_autosuche_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_autosuche_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame_autosucheLayout = new javax.swing.GroupLayout(jFrame_autosuche.getContentPane());
        jFrame_autosuche.getContentPane().setLayout(jFrame_autosucheLayout);
        jFrame_autosucheLayout.setHorizontalGroup(
            jFrame_autosucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_autosucheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame_autosucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_autosucheLayout.createSequentialGroup()
                        .addGroup(jFrame_autosucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_autosuche_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jComboBox_translations, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jFrame_autosucheLayout.setVerticalGroup(
            jFrame_autosucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_autosucheLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_translations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_autosuche_ok)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jFrame_ST.setResizable(false);
        jFrame_ST.setSize(new java.awt.Dimension(230, 100));
        jFrame_ST.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame_STWindowOpened(evt);
            }
        });

        jButton_ST_ok.setText("OK");
        jButton_ST_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ST_okActionPerformed(evt);
            }
        });

        jLabel3.setText("Bitte geben sie den Source Tree ein:");

        jTextField_ST_pfad.setName("jTextfield_ST"); // NOI18N

        jCheckBox_STbeibehalten.setText("Für nächsten Programmstart abspeichern");
        jCheckBox_STbeibehalten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_STbeibehaltenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame_STLayout = new javax.swing.GroupLayout(jFrame_ST.getContentPane());
        jFrame_ST.getContentPane().setLayout(jFrame_STLayout);
        jFrame_STLayout.setHorizontalGroup(
            jFrame_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_STLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_ST_ok)
                    .addComponent(jCheckBox_STbeibehalten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_ST_pfad)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame_STLayout.setVerticalGroup(
            jFrame_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_STLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ST_pfad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_STbeibehalten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton_ST_ok))
        );

        jFrame_Save_in_ST.setResizable(false);
        jFrame_Save_in_ST.setSize(new java.awt.Dimension(300, 125));

        jButton_OK.setText("OK");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_Abbrechen.setText("Abbrechen");
        jButton_Abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbbrechenActionPerformed(evt);
            }
        });

        jLabel6.setText("Dateiname");

        jLabel7.setText("Dateiendung");

        jComboBox_fileFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".ts", ".po" }));

        jScrollPane3.setViewportView(jTextPane_exDateipfad);

        javax.swing.GroupLayout jFrame_Save_in_STLayout = new javax.swing.GroupLayout(jFrame_Save_in_ST.getContentPane());
        jFrame_Save_in_ST.getContentPane().setLayout(jFrame_Save_in_STLayout);
        jFrame_Save_in_STLayout.setHorizontalGroup(
            jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_Save_in_STLayout.createSequentialGroup()
                .addGroup(jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_Save_in_STLayout.createSequentialGroup()
                        .addGroup(jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_Save_in_STLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_Save_in_STLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jFrame_Save_in_STLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Abbrechen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_fileFormat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jFrame_Save_in_STLayout.setVerticalGroup(
            jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_Save_in_STLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_fileFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jFrame_Save_in_STLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Abbrechen)
                    .addComponent(jButton_OK))
                .addContainerGap())
        );

        jFrame_Vergleich.setTitle("Vergleich");
        jFrame_Vergleich.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame_Vergleich.setMinimumSize(new java.awt.Dimension(475, 240));
        jFrame_Vergleich.setPreferredSize(new java.awt.Dimension(475, 240));
        jFrame_Vergleich.setSize(new java.awt.Dimension(475, 240));

        jLabel1.setText("Verlgleichskriterium");

        jComboBox_Vergleichskriterien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Änderungen herrvorheben", "Fehlende Keys"}));

        jComboBox_t1.setModel(new javax.swing.DefaultComboBoxModel<>());
        jComboBox_t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_t1MouseClicked(evt);
            }
        });

        jLabel4.setText("mit");

        jComboBox_t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_t2MouseClicked(evt);
            }
        });

        jButton_vergleiche_Tab.setText("Vergleiche:");
        jButton_vergleiche_Tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vergleiche_TabActionPerformed(evt);
            }
        });

        jTable_vgl_translation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_vgl_translation.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable_vgl_translation);

        jButton1.setText("Ergegnisse speichern unter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Vergleichskriterien, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_vergleiche_Tab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_t1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_t2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Vergleichskriterien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_vergleiche_Tab))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );

        jScrollPaneVgl.setViewportView(jPanel1);

        javax.swing.GroupLayout jFrame_VergleichLayout = new javax.swing.GroupLayout(jFrame_Vergleich.getContentPane());
        jFrame_Vergleich.getContentPane().setLayout(jFrame_VergleichLayout);
        jFrame_VergleichLayout.setHorizontalGroup(
            jFrame_VergleichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jFrame_VergleichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_VergleichLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneVgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jFrame_VergleichLayout.setVerticalGroup(
            jFrame_VergleichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
            .addGroup(jFrame_VergleichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame_VergleichLayout.createSequentialGroup()
                    .addComponent(jScrollPaneVgl)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ETA Translation Suite");
        setIconImages(null);

        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });

        jMenu_datei.setText("Menü");

        jMenuItem_neuesfile.setText("Neu");
        jMenuItem_neuesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_neuesfileActionPerformed(evt);
            }
        });
        jMenu_datei.add(jMenuItem_neuesfile);

        jMenuItem_oeffnen.setText("Übersetzung öffnen");
        jMenuItem_oeffnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_oeffnenActionPerformed(evt);
            }
        });
        jMenu_datei.add(jMenuItem_oeffnen);

        jMenuItem_autosuche.setText("Autosuchen");
        jMenuItem_autosuche.setEnabled(false);
        jMenuItem_autosuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_autosucheActionPerformed(evt);
            }
        });
        jMenu_datei.add(jMenuItem_autosuche);

        jMenuItem1.setText("Vergleichen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_datei.add(jMenuItem1);

        jMenuItem_speichern.setText("Speichern unter");
        jMenuItem_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_speichernActionPerformed(evt);
            }
        });
        jMenu_datei.add(jMenuItem_speichern);

        jMenuItem_speichernST.setText("Speichern in Source Tree");
        jMenuItem_speichernST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_speichernSTActionPerformed(evt);
            }
        });
        jMenu_datei.add(jMenuItem_speichernST);

        jMenuBar1.add(jMenu_datei);

        jMenu_extras.setText("Extras");

        jMenuItem2.setText("Source Tree");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_extras.add(jMenuItem2);

        jMenuBar1.add(jMenu_extras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String manuelleSuche(JTable table) {
        // In dieser Methode wird eine Übersetzungdatei geöffnet, ausgelesen und in die Tabelle jTable1 eingefügt.
        String dateiname = "";

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            BufferedReader br;

            File uebersetzung = fileChooser.getSelectedFile();
            dateiname = uebersetzung.getName();

            if (uebersetzung.getAbsolutePath().endsWith(".po")) {
                table.setModel(new DefaultTableModel(new String[]{"Zeilenummer", "id", "Übersetzung"}, 0));

                try {
                    br = new BufferedReader(new FileReader(uebersetzung));
                    int rowcount = 1;

                    while (true) {

                        String s = br.readLine();

                        //String s ist der eingelesene Zeile aus dem selektierten
                        // .po Files, in der folgende if Anwesiung wird geprüft ob
                        // der Strings das Kürzel msid enthält, wenn des stimmt
                        // wird überprüft ob die folgende Zeile des Kürzel msgstr enthält.
                        // Wenn das wieder Stimmt dann wird der String s und der
                        // String next in der jTable1 hinzugefügt
                        if (s != null) {
                            rowcount++;
                            if (s.contains("msgid")) {
                                String next = br.readLine();

                                if (next != null && next.contains("msgstr")) {

                                    s = s.substring(7, s.length() - 1);
                                    next = next.substring(8, next.length() - 1);
                                    ((DefaultTableModel) table.getModel()).addRow(new String[]{Integer.toString(rowcount - 1) + "-" + Integer.toString(rowcount), s, next});
                                }
                            }
                        } else {
                            break;
                        }
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (uebersetzung.getAbsolutePath().endsWith(".ts")) {

                table.setModel(new DefaultTableModel(new String[]{"zeilennummer", "filename", "Quelle", "Übersetzung"}, 0));

                try {
                    String pfad = uebersetzung.getAbsolutePath();
                    System.out.println(pfad);
                    Document tsfile = new SAXBuilder().build(pfad);
                    Element ts = tsfile.getRootElement();
                    Element context = ts.getChild("context");
                    List<Element> messages = context.getChildren("message");
                    for (Element e : messages) {
                        ((DefaultTableModel) table.getModel()).addRow(new String[]{
                            e.getChild("location").getAttributeValue("line"),
                            e.getChild("location").getAttributeValue("filename"),
                            e.getChildText("source"),
                            e.getChildText("translation")

                        });
                    }

                } catch (JDOMException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
        return dateiname;
    }

    private String autosuche(JTable table) {
        // Hier werden die Übersetzungen in die Table geladen
        jFrame_autosuche.setVisible(true);

        DefaultComboBoxModel<String> uebersetzungen = (DefaultComboBoxModel) jComboBox_translations.getModel();
        String dateiname = "";

        if (uebersetzungen.getSize() > 0) {
            BufferedReader br;
            File cFile = new File(sourceTree + "//" + uebersetzungen.getSelectedItem());
            dateiname = cFile.getName();

            if (cFile.getAbsolutePath().endsWith(".po")) {
                table.setModel(new DefaultTableModel(new String[]{"Zeilenummer", "id", "Übersetzung"}, 0));
                try {
                    br = new BufferedReader(new FileReader(cFile));
                    int rowcount = 1;

                    while (true) {

                        String s = br.readLine();

                        //String s ist der eingelesene Zeile aus dem selektierten
                        // .po Files, in der folgende if Anwesiung wird geprüft ob
                        // der Strings das Kürzel msid enthält, wenn des stimmt
                        // wird überprüft ob die folgende Zeile des Kürzel msgstr enthält.
                        // Wenn das wieder Stimmt dann wird der String s und der
                        // String next in der jTable1 hinzugefügt
                        if (s != null) {
                            rowcount++;
                            if (s.contains("msgid")) {
                                String next = br.readLine();

                                if (next != null && next.contains("msgstr")) {

                                    s = s.substring(7, s.length() - 1);
                                    next = next.substring(8, next.length() - 1);
                                    ((DefaultTableModel) table.getModel()).addRow(new String[]{Integer.toString(rowcount - 1) + "-" + Integer.toString(rowcount), s, next});
                                }
                            }
                        } else {
                            break;
                        }
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (cFile.getAbsolutePath().endsWith(".ts")) {

                table.setModel(new DefaultTableModel(new String[]{"zeilennummer", "filename", "Quelle", "Übersetzung"}, 0));

                try {
                    String pfad = cFile.getAbsolutePath();
                    System.out.println(pfad);
                    Document tsfile = new SAXBuilder().build(pfad);
                    Element ts = tsfile.getRootElement();
                    Element context = ts.getChild("context");
                    List<Element> messages = context.getChildren("message");
                    for (Element e : messages) {
                        ((DefaultTableModel) table.getModel()).addRow(new String[]{
                            e.getChild("location").getAttributeValue("line"),
                            e.getChild("location").getAttributeValue("filename"),
                            e.getChildText("source"),
                            e.getChildText("translation")

                        });
                    }

                } catch (JDOMException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
        jFrame_autosuche.setVisible(false);
        return dateiname;
    }


    private void jMenuItem_oeffnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_oeffnenActionPerformed
        tspoFile temp = new tspoFile();
        temp.setFile_name(manuelleSuche(temp.getDaten()));

        if (!temp.getFile_name().isEmpty()) {
            jTabbedPane.setTitleAt(0, temp.getFile_name());
            tspofiles.add(temp);
        }
    }//GEN-LAST:event_jMenuItem_oeffnenActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Wenn man auf den Menüeintrag Autosuchen klickt öffnet sich ein kleines Eingabefenster
        jFrame_ST.setVisible(true);
        jFrame_ST.setSize(320, 230);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton_ST_abbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ST_abbrActionPerformed
        // Wenn man abbrechen klickt wird der Source Tree nicht gespeichert
        jFrame_ST.setVisible(false);
    }//GEN-LAST:event_jButton_ST_abbrActionPerformed

    private void jMenuItem_autosucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_autosucheActionPerformed
        searchST();
    }//GEN-LAST:event_jMenuItem_autosucheActionPerformed

    public void searchST() {
        // Hier wird im Source Tree nach Übersetzungen gesucht
        jFrame_autosuche.setSize(350, 121);
        jFrame_autosuche.setVisible(true);
        jComboBox_translations.setModel(new DefaultComboBoxModel<String>());
 
        File sT = new File(sourceTree);
        String[] files = sT.list();

        for (String file : files) {
            if (file.endsWith(".po") || file.endsWith(".ts")) {
                ((DefaultComboBoxModel) jComboBox_translations.getModel()).addElement(file);
            }
        }

        if (((DefaultComboBoxModel) jComboBox_translations.getModel()).getSize() == 0) {
            jFrame_autosuche.setVisible(false);
            JOptionPane.showMessageDialog(this, "Es wurden im Source Tree keine Übersetzungen gefunden", "Warnung", JOptionPane.WARNING_MESSAGE);

        }
    }

    private void jButton_autosuche_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_autosuche_okActionPerformed
        //hier wird eine Datei eingelesen und in Tabellen in eine TabbedPane hinzugefügt
        jTabbedPane.setVisible(true);
        tspoFile temp = new tspoFile();

        temp.getDaten().setModel(new DefaultTableModel(new String[]{"Zeilenummer", "id", "Übersetzung"}, 0));

        temp.setFile_name(autosuche(temp.getDaten()));
        System.out.println(temp.getDaten().getColumnCount());
        JScrollPane sp = new JScrollPane();
        sp.setViewportView(temp.getDaten());
        temp.getDaten().setFillsViewportHeight(true);
        temp.getDaten().setEditingColumn(0);
        temp.getDaten().setEditingColumn(1);
        if (!temp.getFile_name().isEmpty()) {
            jTabbedPane.addTab(temp.getFile_name(), sp);
            tspofiles.add(temp);
        }

    }//GEN-LAST:event_jButton_autosuche_okActionPerformed

    private void jButton_ST_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ST_okActionPerformed
        // Wenn man OK klickt wird der Source Tree gespeichert
        //mithilfe des eingegeben Strings wird ein File ersellt
        //damit ist möglich zu überprüfen ob der sourctree existiert bzw.
        //nicht schreib/lesegeschützt ist
        sourceTree = jTextField_ST_pfad.getText();
        File f = new File(sourceTree);

        if (f.isDirectory() && f.exists() && f.canRead() && f.canWrite()) {
            jFrame_ST.setVisible(false);
            jMenuItem_autosuche.setEnabled(true);

        } else if (!f.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Source Tree ist keine Verzeichniss", "Eingabehler", JOptionPane.ERROR_MESSAGE);
            sourceTree = "";
            jTextField_ST_pfad.setText("");
        } else if (!f.exists()) {
            JOptionPane.showMessageDialog(this, "Source Tree existiert nicht", "Eingabehler", JOptionPane.ERROR_MESSAGE);
            sourceTree = "";
            jTextField_ST_pfad.setText("");
        } else if (!f.canRead()) {
            JOptionPane.showMessageDialog(this, "Source Tree ist lesegeschützt", "Eingabehler", JOptionPane.ERROR_MESSAGE);
            sourceTree = "";
            jTextField_ST_pfad.setText("");

        } else if (!f.canWrite()) {
            JOptionPane.showMessageDialog(this, "Source Tree ist schreibgeschützt", "Eingabehler", JOptionPane.ERROR_MESSAGE);
            sourceTree = "";
            jTextField_ST_pfad.setText("");

        }

        if (jCheckBox_STbeibehalten.isEnabled()) {
            ObjectOutputStream oos;
            try {
                oos = new ObjectOutputStream(new FileOutputStream("ST.txt"));
                oos.writeObject(sourceTree);
                oos.flush();

            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            File st_alt = new File("ST.txt");
            st_alt.deleteOnExit();
        }

    }//GEN-LAST:event_jButton_ST_okActionPerformed

    private void jCheckBox_STbeibehaltenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_STbeibehaltenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_STbeibehaltenActionPerformed

    private void jFrame_STWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame_STWindowOpened


    }//GEN-LAST:event_jFrame_STWindowOpened

    private void jMenuItem_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_speichernActionPerformed
        jTabbedPane.setVisible(true);
        JFileChooser exportFileChooser = new JFileChooser(sourceTree);
        exportFileChooser.setAcceptAllFileFilterUsed(false);
        exportFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        exportFileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".ts Übersetzungen (.ts)", "ts"));
        exportFileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".po Übersetzungen (.po)", "po"));

        if (exportFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

            if (!tspofiles.isEmpty() && !jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()).equals("*neu")) {
                String sff = (((FileNameExtensionFilter) exportFileChooser.getFileFilter()).getExtensions())[0];
                tspoFile neu = new tspoFile(exportFileChooser.getCurrentDirectory().getAbsolutePath() + "//" + exportFileChooser.getSelectedFile().getName() + "." + sff,jTable_tab_start);
                for (tspoFile tspofile : tspofiles) {
                    if (tspofile.getFile_name().endsWith(jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()))) {
                       // Methoden.exportPOfile(neu);
                       // break;
                        String m="Datei ist bereits vorhanden. Möchten Sie diese Überschreiben oder möchten Sie die Datei unter einen neuen Name abspeichern?";
             
                    Object[] options={"Überschreiben","neuer Namen","Abbrechen"};
                    switch(JOptionPane.showOptionDialog(rootPane,m, "Konflikt", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,null,options,options[2])){
                        case JOptionPane.YES_OPTION:
                            System.out.println("JA MAN");
                               neu = new tspoFile(sourceTree + jTextPane_exDateipfad.getText() + jComboBox_fileFormat.getSelectedItem(),jTable_tab_start);
                              Methoden.exportPOfile (tspofile);
                            break;
                        case JOptionPane.NO_OPTION:
                            System.out.println("USER SAGT NEIN");
                            break;
                        default:
                            break;
                    }
                  
                    break;

                    }
                }
                tspofiles.add(neu);
            } else if (jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()).equals("*neu")) {
                String sff = (((FileNameExtensionFilter) exportFileChooser.getFileFilter()).getExtensions())[0];
                tspoFile neu=new tspoFile(exportFileChooser.getCurrentDirectory().getAbsolutePath() + "//" + exportFileChooser.getSelectedFile().getName() + "." + sff, jTable_tab_start);
                tspofiles.add(neu);
                if (sff.equals("ts")) {

                    Methoden.exportTSfile(neu);
                    jTabbedPane.setTitleAt(jTabbedPane.getSelectedIndex(), exportFileChooser.getSelectedFile().getName() + "." + sff);
                    JOptionPane.showMessageDialog(rootPane, "Abspeicherung erfolgreich!", "Information", JOptionPane.INFORMATION_MESSAGE);

                } else if (sff.equals("po")) {
                    Methoden.exportPOfile(neu);
                    jTabbedPane.setTitleAt(jTabbedPane.getSelectedIndex(), exportFileChooser.getSelectedFile().getName() + "." + sff);
                    JOptionPane.showMessageDialog(rootPane, "Abspeicherung erfolgreich!", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Abspeicherung nicht möglich da keine Daten vorhanden sind", "FEHLER!!!", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jMenuItem_speichernActionPerformed

    private void jMenuItem_speichernSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_speichernSTActionPerformed
        jFrame_Save_in_ST.setVisible(true);

    }//GEN-LAST:event_jMenuItem_speichernSTActionPerformed

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        jFrame_Save_in_ST.setVisible(false);
        if (!tspofiles.isEmpty() && !jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()).equals("*neu")) {
            for (tspoFile tspofile : tspofiles) {
                if (tspofile.getFile_name().endsWith(jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()))) {
                    String m="Datei ist bereits vorhanden. Möchten Sie diese Überschreiben oder möchten Sie die Datei unter einen neuen Name abspeichern?";
                    
                    Object[] options={"Überschreiben","neuer Namen","Abbrechen"};
                    switch(JOptionPane.showOptionDialog(rootPane,m, "Konflikt", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,null,options,options[2])){
                        case JOptionPane.YES_OPTION:
                              tspoFile neu = new tspoFile(sourceTree + jTextPane_exDateipfad.getText() + jComboBox_fileFormat.getSelectedItem(),jTable_tab_start);
                              Methoden.exportPOfile (tspofile);
                            break;
                        case JOptionPane.NO_OPTION:
                            System.out.println("USER SAGT NEIN");
                            break;
                        default:
                            break;
                    }
                  
                    break;

                }
            }
           
        } else if (jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()).equals("*neu")) {
            tspoFile neu = new tspoFile(sourceTree + jTextPane_exDateipfad.getText() + jComboBox_fileFormat.getSelectedItem(),jTable_tab_start);
            tspofiles.add(neu);
            if (jComboBox_fileFormat.getSelectedItem().equals("ts")) {

                Methoden.exportTSfile(neu);
                jTabbedPane.setTitleAt(jTabbedPane.getSelectedIndex(), sourceTree + jTextPane_exDateipfad.getText() + jComboBox_fileFormat.getSelectedItem());
                JOptionPane.showMessageDialog(rootPane, "Abspeicherung erfolgreich!", "Information", JOptionPane.INFORMATION_MESSAGE);

            } else if (jComboBox_fileFormat.getSelectedItem().equals("po")) {
                Methoden.exportPOfile(neu);
                jTabbedPane.setTitleAt(jTabbedPane.getSelectedIndex(), sourceTree + jTextPane_exDateipfad.getText() + jComboBox_fileFormat.getSelectedItem());
                JOptionPane.showMessageDialog(rootPane, "Abspeicherung erfolgreich!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Abspeicherung nicht möglich da keine Daten vorhanden sind", "FEHLER!!!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_AbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbbrechenActionPerformed
        jFrame_Save_in_ST.setVisible(false);
    }//GEN-LAST:event_jButton_AbbrechenActionPerformed

    private void jMenuItem_neuesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_neuesfileActionPerformed
        int tc = jTabbedPane.getTabCount();
        jTabbedPane.setVisible(true);
        JScrollPane jScrollPane_TabellenTab1 = new javax.swing.JScrollPane();
        jScrollPane_TabellenTab1.setViewportView(jTable_tab_start);
        jTabbedPane.addTab("*neu", jScrollPane_TabellenTab1);
        jTabbedPane.setSelectedIndex(tc);

    }//GEN-LAST:event_jMenuItem_neuesfileActionPerformed

    private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
        if (jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex()).equals("Vergleich")) {
            int tab_count = jTabbedPane.getTabCount();

            LinkedList<String> all_tabnames = new LinkedList<>();

            for (int i = 0; i < tab_count; i++) {
                String current_tname = jTabbedPane.getTitleAt(i);
                if (!current_tname.equals("*neu") && !current_tname.equals("Vergleich") && !all_tabnames.contains(current_tname)) {
                    all_tabnames.add(current_tname);
                }
            }

            jComboBox_t1.setModel(new DefaultComboBoxModel<String>());

            for (String s : all_tabnames) {
                ((DefaultComboBoxModel) jComboBox_t1.getModel()).addElement(s);
            }

            jComboBox_t2.setModel(new DefaultComboBoxModel<String>());

            for (String s : all_tabnames) {
                ((DefaultComboBoxModel) jComboBox_t2.getModel()).addElement(s);
            }

        }
    }//GEN-LAST:event_jTabbedPaneMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Bei diesen Event werden die Unterschiede aus der Tabelle vgl_translation
        //entnommen und in einen gewünschten Ordner abgespeichert
        jTabbedPane.setVisible(true);
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter(".csv File", ".csv"));
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            Methoden.exportiere_unterschiede(chooser.getSelectedFile().getPath(), jTable_vgl_translation);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_vergleiche_TabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vergleiche_TabActionPerformed
        //Hier werden die Selektierten Tabellen vergliche nach den Selektierten Kriterien
        // tspofile: eine Klasse in den eine Tabelle und ein String name enthalten ist
        // tspofiles: eine LinkedList mit tspofiles
        String[] sel_files = new String[2];
        sel_files[0] = (String) jComboBox_t1.getSelectedItem();
        sel_files[1] = (String) jComboBox_t2.getSelectedItem();
        Methoden.vergleiche((String) jComboBox_Vergleichskriterien.getSelectedItem(), jTable_vgl_translation, tspofiles, jLabel5, sel_files);
    }//GEN-LAST:event_jButton_vergleiche_TabActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jFrame_Vergleich.setVisible(true);
        
        jComboBox_t1.removeAllItems();
        for (int i=0;i<jTabbedPane.getTabCount();i++) {
            jComboBox_t1.insertItemAt(jTabbedPane.getTitleAt(i), i);
        }
        
        jComboBox_t2.removeAllItems();
        for (int i=0;i<jTabbedPane.getTabCount();i++) {
            jComboBox_t2.insertItemAt(jTabbedPane.getTitleAt(i), i);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBox_t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_t1MouseClicked
        jComboBox_t1.removeAllItems();
        for (int i=0;i<jTabbedPane.getTabCount();i++) {
            jComboBox_t1.insertItemAt(jTabbedPane.getTitleAt(i), i);
        }
    }//GEN-LAST:event_jComboBox_t1MouseClicked

    private void jComboBox_t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_t2MouseClicked
        jComboBox_t2.removeAllItems();
        for (int i=0;i<jTabbedPane.getTabCount();i++) {
            jComboBox_t2.insertItemAt(jTabbedPane.getTitleAt(i), i);
        }
    }//GEN-LAST:event_jComboBox_t2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Abbrechen;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_ST_abbr;
    private javax.swing.JButton jButton_ST_ok;
    private javax.swing.JButton jButton_autosuche_ok;
    private javax.swing.JButton jButton_vergleiche_Tab;
    private javax.swing.JCheckBox jCheckBox_STbeibehalten;
    private javax.swing.JComboBox<String> jComboBox_Vergleichskriterien;
    private javax.swing.JComboBox<String> jComboBox_fileFormat;
    private javax.swing.JComboBox<String> jComboBox_t1;
    private javax.swing.JComboBox<String> jComboBox_t2;
    private javax.swing.JComboBox<String> jComboBox_translations;
    private javax.swing.JFrame jFrame_ST;
    private javax.swing.JFrame jFrame_Save_in_ST;
    private javax.swing.JFrame jFrame_Vergleich;
    private javax.swing.JFrame jFrame_autosuche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_autosuche;
    private javax.swing.JMenuItem jMenuItem_neuesfile;
    private javax.swing.JMenuItem jMenuItem_oeffnen;
    private javax.swing.JMenuItem jMenuItem_speichern;
    private javax.swing.JMenuItem jMenuItem_speichernST;
    private javax.swing.JMenu jMenu_datei;
    private javax.swing.JMenu jMenu_extras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneVgl;
    private javax.swing.JTabbedPane jTabbedPane;
    public javax.swing.JTable jTable_vgl_translation;
    private javax.swing.JTextField jTextField_ST_pfad;
    private javax.swing.JTextPane jTextPane_exDateipfad;
    // End of variables declaration//GEN-END:variables

}
